# Generated by Django 4.2.2 on 2023-06-25 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='post_date',
            field=models.DateField(default=datetime.date(2023, 6, 25)),
        ),
    ]
